### ISSUE TITLE
Durante o Combate o mud esta dando crash

### ISSUE THREAD

**Issue by Magrog** [d3m4/wardome#9]
Sem motivo aparente (sem usar skills nem objetos) durante certo tempo em combate o mud da crash.

**Comment by guilindner** [comment]
resolvido no commit f0686dca2c863d47084d14f917d76fee99eb1b92

**Comment by Magrog** [comment]
Qual o endereço do mud?

Em 18/06/2017 15:02, "Guilherme Lindner" <notifications@github.com>
escreveu:

resolvido no commit f0686dc
<https://github.com/d3m4/wardome/commit/f0686dca2c863d47084d14f917d76fee99eb1b92>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/d3m4/wardome/issues/9#issuecomment-309292795>, or mute
the thread

**Comment by d3m4** [comment]
Hoje, ate onde sei o mud nao está publicado.
Esse repo não é o mais novo inclusive, mas nao sei se posso publicar o outro
